repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix, --unsafe-fixes]
        exclude: ^notebooks/
      - id: ruff-format
        exclude: ^notebooks/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^(notebooks/|\.all-contributorsrc$)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
        exclude: ^notebooks/
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^(notebooks/|\.all-contributorsrc$)
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^(notebooks/|\.all-contributorsrc$)
      - id: trailing-whitespace
        exclude: ^(notebooks/|\.all-contributorsrc$)
